- name: cp kubelet.service to systemd 
  become_user: root
  become: yes
  template: src=kubelet.service.{{ kubelet_version | regex_search('(v[0-9]+\.[0-9]+)') }}.j2 dest="{{ debian_systemd_dir }}/kubelet.service.d/10-kubeadm.conf"

- name: systemctl daemon-reload
  become: yes
  shell: systemctl daemon-reload

- name: systemctl enable kubelet
  become: yes
  shell: systemctl enable kubelet
  
- name: systemctl restart kubelet
  become: yes
  shell: systemctl restart kubelet


